### ISSUE TITLE
Improve readability of lengthened text

### ISSUE THREAD

**Issue by M0ns1gn0r** [martincostello/Pseudolocalizer#31]
AFAIK the symbol ẋ is currently used to lengthen the texts. This symbol, however, makes it harder to read the original texts. What about changing it to something less obtrusive, e.g. a dot?

Then instead of this:
`[Þļéåšéẋẋ çöñƒîŕɱẋẋẋ ţĥîšẋẋ é‐ɱåîļẋẋ åððŕéššẋẋẋ ƀýẋ çļîçķîñĝẋẋẋ ţĥéẋ ƒöļļöŵîñĝẋẋẋ ļîñķ∶ẋẋ]`

We would get:
`[Þļéåšé.. çöñƒîŕɱ... ţĥîš.. é‐ɱåîļ.. åððŕéšš... ƀý. çļîçķîñĝ... ţĥé. ƒöļļöŵîñĝ... ļîñķ∶..]`

Or even allow to specify that symbol in the command line.

**Comment by martincostello** [comment]
Hi @M0ns1gn0r - making this a configurable option sounds reasonable, I’ll look into it sometime in the next week.

Thanks for the feedback!

**Comment by martincostello** [comment]
Comments welcome on #32.
