### ISSUE TITLE
Mirror - {}, [], (), etc. do not get flipped

### ISSUE THREAD

**Issue by aormsby** [martincostello/Pseudolocalizer#75]
When I mirror my text, surrounding items like {}, [], (), etc. don't get flipped around to accommodate the change in direction, which can create placeholder issues.

Example: My name is {0}.
Mirrored: .}0{ si eman yM
Expected: .{0} si eman yM

A simple char switch should do the trick if possible. I suppose there may be other characters that have this issue, but these are the ones I noticed.

**Comment by aormsby** [comment]
Oh, hmm... I didn't realize you forked this. Would this bug be better in the original repo?

**Comment by martincostello** [comment]
The original hasn't had any activity for 8 years, which is why I forked it in the first place to make it work for .NET Core.

This repo is the source of the NuGet packages so it's the right place.

**Comment by aormsby** [comment]
Ah, I see. Thanks for that then. :)

**Comment by martincostello** [comment]
I've opened #82 to resolve this - could you take a look and check whether or not the proposed changes handle your use cases?

**Comment by aormsby** [comment]
Yeah, that looks like what I need and then some more. Nice catch keeping the HTML tags from flipping, too. I hadn't even considered that.

And now that you've gone down this rabbit hole a little, I have an additional thought - what about escape characters? Much like HTML tags, these could also benefit from being ignored when mirroring. However, you'd have to identify them as such while keeping non-escape '\' flipped as normal. It could be more extensive work. That's not anything I'm looking for, but it's food for thought.

In any case, the current solution would be great for my needs. :)

**Comment by martincostello** [comment]
Cool thanks for checking.

I'll leave the escaping as a thing to maybe come back to at some point in the future.

I'll merge the PR and look at pushing out a new release with the changes next week 👍

**Comment by martincostello** [comment]
v0.3.0 has been published which contains the fixes for this issue - thanks again for reporting it.

https://www.nuget.org/packages/PseudoLocalize/0.3.0
